### ISSUE TITLE
better defaults in config.sh ?

### ISSUE THREAD

**Issue by bukzor** [drwilly/redo#3]
You might use some/all of these as default values in your config.sh:

```
--- config.sh
+++ config.sh
@@ -1,7 +1,7 @@
-PREFIX="$HOME"
+PREFIX="$HOME/prefix/credo"
 
 CC="clang"
 CFLAGS="-g -O0 -Wall -pedantic"
 
-INC=""
-LIBPATH=""
+INC="-I$PREFIX/include"
+LIBPATH="-L$PREFIX/lib -Wl,-rpath=\\\$ORIGIN/../lib"
```

**Comment by drwilly** [comment]
Care to elaborate on the advantages of that specific setup?

**Comment by bukzor** [comment]
The -I and -L are entirely required if anyone is using a prefix
installation at all, and won't harm anything if their prefix happens to be
/usr.

The rpath is just nice to have, but allows one to put $PREFIX/bin on the
path without worrying about LD_LIBRARY_PATH or static linking, plus makes
the prefix dir relocatable without recompilation. Just a nicety.

The default value for prefix might be silliness, but it's what I'm using
and seems like a more reasonable default than littering the home directory
with no uninstall option.
