### ISSUE TITLE
target in subdirectory always out of date

### ISSUE THREAD

**Issue by bukzor** [drwilly/redo#4]
Maybe I'm using this thing wrong, but I don't think I am. The below behavior feels wrong. Just because `1` is no longer in my $PWD it's being considered out of date by redo.

```
$ mkdir demo && cd demo

$ echo 'set -x && echo 1' > 1.do

$ chmod 755 1.do

$ redo-ifchange 1
redo    1.do:1  ...
+ echo 1

$ redo-ifchange 1

$ redo-ifchange 1

$ cd ..

$ redo-ifchange demo/1
redo    1.do:demo/1     ...
+ echo 1

$ redo-ifchange demo/1
redo    1.do:demo/1     ...
+ echo 1

$ redo-ifchange demo/1
redo    1.do:demo/1     ...
+ echo 1
```

**Comment by drwilly** [comment]
when redo builds a target it first `cd`s to the directory in which the `.do`file is located.
All prereqs are stored relative to that `$PWD`. Apparently I forgot to do the same when looking up those prereqs.
On a similar note, `cd`ing inside a `.do`script currently is a big no-no.

Anyway, looks like I'm in for some more path-juggling.

**Comment by bukzor** [comment]
I thought prereqs were stored as a sibling to the target, if you do that
and make all paths relative to their prereq file, it should be all good,
no? I can help if you show me how to add a regression test.

**Comment by drwilly** [comment]
issue should be fixed now.
I'm not 100% happy with the fix since I had to copy some code from redo.c to prereqs.c, but that will require some more thought.

**Comment by bukzor** [comment]
Fix confirmed. Thanks!
